### PR TITLE
Support -pextraArgs=-foo|-bar or -pextraArgs=@argsFile

### PR DESCRIPTION
**Pull request by retronym**

### CODE REVIEW

**Comment by retronym** [comment]
Motivation was an easy way to test out:

```
sbt 'set scalaVersion in compilation := "2.12.3-bin-d1ec01a-SNAPSHOT"' 'hot -psource=scalap -f3 -pextraArgs=-Yno-generic-signatures|-no-specialization -jvmArgs -XX:MaxInlineLevel=18'
```

Which gives another 12% performance bump over 2.13.3-pre.

Caveats:
  - `-no-specialization` results in less efficient code for calls to specialized methods
  - `-Yno-generic-sigs` sacrifices interop wth Java generics

For local development builds, these tradeoffs might be palatable.

Rough numbers attributing the gains:

```
      


             _______________ 723 ____________            -XX:MaxInlineLevel=18
            /                                \           
 754 ------<                                  >-- 660  
            \_______________ 745 ____________/           -Yno-generic-signatures
             \                              /
              \____________  720 __________/             -no-specialization


```

**Comment by lrytz** [comment]
> 12% performance bump

Juicy..!

The issue solved here is that you cannot pass the args space-separated, right?

**Comment by lrytz** [comment]
Another one for dev-mode (which we currently don't have a flag for) would be to skip emitting the InnerClass table (https://github.com/scala/scala/blob/v2.12.2/src/compiler/scala/tools/nsc/backend/jvm/GenBCode.scala#L253)

**Comment by retronym** [comment]
> The issue solved here is that you cannot pass the args space-separated, right?

Yep, passing spaces in args to input tasks seems hard in SBT.

> Another one for dev-mode (which we currently don't have a flag for) would be to skip emitting the InnerClass table 

Good one! Another skippable (albeit currently flagless) part of the backend is emission of static fowarders and mirror classes for Java interop.

**Pull request merged**
