### PR TITLE
Add a comparative Java vs Scala benchmark

### PR DESCRIPTION
**Pull request by retronym**
9kloc of Java code faithfully transliterated to Scala by the
good folks at Scala Native and put to use in twitter/reasonable-scala
as a comparative benchmark.

I've fleshed out the Javac benchmark driver to let us
run this.

```
> compilation/jmh:run scala.tools.nsc.JavacBenchmark -psource=re2j

> hot -psource=re2s
```

On my machine, scalac gets to 7500 loc/s. Javac hits a whopping 130kloc/s.

### CODE REVIEW

**Comment by xeno-by** [comment]
Cool stuff! Thanks for pinging :)

The credit for porting belongs to @densh (https://github.com/scala-native/scala-native/pull/894). We just used his work.

**Comment by retronym** [comment]
Thanks, I've updated the licence notice and credits.

**Comment by retronym** [comment]
Just pushed some tweaks to the new examples that make it a fairer comparison:
  - Use private[this] fields in Scala 
  - avoid use of lazy vals in Scala
  - Use compile time constants in Scala, as per the original version

The compile time is slightly better, 8300 loc/s. 

The Scala version still emits 592k of bytecode vs 364k for the Java version. 

I pushed another commit to use `Array.apply(Int, Int*)` rather than the gener version you get with `Array.apply[Int]`, which drops the generated code to 488K. But the compile times get quite a bit worse, probably due to overload resolution.

This all points to some areas for improvement, but also to the fact that this corpus might be dominated by our weaknesses around embedding tables in arrays in source code.

**Comment by retronym** [comment]
I pushed another commit that stubs out the big array "literals" from both the Java and Scala implenentations of `UnicodeTables`. Scalac gets to 14kloc/s for the remaining 5kloc; javac drops to 77kloc/s.

Javac benefits in this case from the dedicated syntax for array initialization, we pay a price for making them look just like regular applications. We can/should see if we can reduce that price, but I think I'll leave the benchmark in the final state to be more representative of "normal" code that doesn't have enourmous unicode tables embedded.

**Pull request merged**
